### PR TITLE
Remove up-core-api dependency and pull it from git repo

### PR DESCRIPTION
**Pull request by neelam-kushwah**
#8

### CODE REVIEW

**Comment by neelam-kushwah** [comment]
@halimragab and @stevenhartley, please review.

**Review by stevenhartley — APPROVED** [review]
LGTM, thanks @neelam-kushwah !

**Comment by neelam-kushwah** [comment]
Under discussion

**Comment by stevenhartley** [comment]
@neelam-kushwah , I pulled and tried it and noticed that only the uProtocol protos are getting generated (and not the COVESA/uService ones), can you check on your side?

**Review by stevenhartley — APPROVED** [review]
LGTM!

**Pull request merged**
